name: Release

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Install
      run: yarn install

    - name: Release API
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn workspace @shift-code/api run build
        yarn workspace @shift-code/api run release -- --dry-run

    - name: Release Source
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn workspace @shift-code/source run build
        yarn workspace @shift-code/source run release -- --dry-run

    - name: Release CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn workspace @shift-code/cli run build
        yarn workspace @shift-code/cli run release -- --dry-run
